spring.application.name=pdfai
spring.profiles.active=dev
spring.datasource.url=<uri>
spring.datasource.username=<username>
spring.datasource.password=<password>
spring.servlet.multipart.max-file-size=<size-in-mb>
spring.servlet.multipart.max-request-size=<size-in-mb>
spring.server.port=<port>